#!/bin/sh

SOURCE_DIR=$(dirname ${BASH_SOURCE[0]})
WORKING_DIR=`pwd`

CONFIG_FILE=$SOURCE_DIR/ab-test.conf.tmp
LOG_FILE=$WORKING_DIR/`date +%Y%m%d`_ab-test.log

> $CONFIG_FILE
echo "group ab_test:" >> $CONFIG_FILE
echo "    module ab_group" >> $CONFIG_FILE

$SOURCE_DIR/m3highload-test --config $CONFIG_FILE --host cakestory-staging.plamee.com --verbose  --log $LOG_FILE

rm -f $CONFIG_FILE

echo
echo "Log saved into $LOG_FILE"
echo

exit 0