#!/bin/sh

SOURCE_DIR=$(dirname ${BASH_SOURCE[0]})
WORKING_DIR=`pwd`

CONFIG_FILE=$SOURCE_DIR/og-test.conf.tmp
LOG_FILE=$WORKING_DIR/og-test.log

> $CONFIG_FILE
echo "group opengraph:" >> $CONFIG_FILE
echo "    module tiers" >> $CONFIG_FILE

$SOURCE_DIR/m3highload-test --config $CONFIG_FILE --host m3highload-master.test.nsk.plamee.com --verbose  --log $LOG_FILE

rm -f $CONFIG_FILE

echo
echo "Log saved into $LOG_FILE"
echo

exit 0